name: Build, Push & Test OrangeHRM

on:
    push:
        branches: ["master"]
        
        
jobs:
    e2e-test:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                browser: [chrome, firefox]
        
        steps:
            - name: Checkout orangehrm code
              uses: actions/checkout@v4
              
            - name: Install jq
              run: sudo apt-get update && sudo apt-get install -y jq

              
            - name: Get latest version
              id: get_version
              run: |
                git fetch --tags
                VERSION=$(git tag | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
                if [ -z "$VERSION" ]; then
                VERSION="v1.0.0"
                fi
                echo "CURRENT_VERSION=$VERSION" >> $GITHUB_ENV
                
            - name: Bump version
              if: success()
              run: |
                VERSION=${CURRENT_VERSION#v}
                MAJOR=$(echo $VERSION | cut -d. -f1)
                MINOR=$(echo $VERSION | cut -d. -f2)
                PATCH=$(echo $VERSION | cut -d. -f3)
                PATCH=$((PATCH+1))
                NEW_VERSION="$MAJOR.$MINOR.$PATCH"
                echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
                
            - name: Set temp tag
              run: echo "TEMP_TAG=temp-${GITHUB_SHA}" >> $GITHUB_ENV
              
            - name: Pull cache (stable)
              run: docker pull my-app:stable || true

            - name: Build & Push temp (with cache)
              run: |
                docker build \
                --cache-from=my-app:stable \
                -t my-app:$TEMP_TAG .
                docker push my-app:$TEMP_TAG
            
            - name: Stop container with label orangehrm
              run: sudo docker ps -q --filter "label=app=orangehrm" | xargs -r docker stop
              
            - name: Remove OrangeHRM
              run: sudo docker ps -aq --filter "label=app=orangehrm" | xargs -r docker rm
              
            - name: Get traefik từ repo
              uses: actions/checkout@v4
              with:
                repository: tamahouse/orangehrm-traefik
                path: orangehrm-traefik
                token: ${{secrets.GITHUB_TOKEN}}
              
            - name: Deploy
              run: |
                cd orangehrm-traefik
                export TAG=$TEMP_TAG
                echo "Deploy version: $TAG"
                docker compose up -d
            
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
                
            - name: Get code auto từ repo
              uses: actions/checkout@v4
              with:
                repository: tamahouse/orangehrm-demo-automation
                path: automation
                token: ${{secrets.GITHUB_TOKEN}}
                
            - name: Verify automation repo
              run: |
                echo "=== ROOT ==="
                ls -la
                echo "=== AUTOMATION ==="
                ls -la automation || echo "❌ automation NOT FOUND"
                
            - name: Start Selenium
              run: sudo docker run -d -p 4444:4444 --name selenium selenium/standalone-${{ matrix.browser }}
                
            - name: Run Test
              working-directory: automation
             # run: mvn clean test
             run: mvn clean test -Pregression -Devn=staging -Dbrowser=${{ matrix.browser }} -DbaseUrl=https://chaseqa.duckdns.org -DremoteUrl=http://localhost:4444
         
            - name: Copy allure results to VPS
              if: always()
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_KEY }}
                source: "automation/allure-results"
                target: "/opt/allure-results/${{ env.TEMP_TAG }}"
                
            - name: Generate Allure Report on VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                    TAG=${{ env.TEMP_TAG }}
                    allure generate /opt/allure-results/$TAG \
                    -o /opt/allure-reports/build-$TAG --clean
                    rm -rf /opt/allure-reports/latest
                    cp -r /opt/allure-reports/build-$TAG /opt/allure-reports/latest
                    
            - name: Login Docker Hub
              if: success()
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PAT}}
                    
            - name: Promote image
              if: success()
              run: |
                docker tag my-app:$TEMP_TAG my-app:$NEW_VERSION
                docker push my-app:$NEW_VERSION
                docker push my-app:stable
                
            - name: Create git tag
              if: success()
              run: |
                git config user.name "tamahouse"
                git config user.email "tamahosue@github.com"
                git tag v$NEW_VERSION
                git push origin v$NEW_VERSION
                    
            
            - name: Rollback
              if: failure()
              run: |
                cd orangehrm-traefik
                export TAG=stable
                docker compose pull
                docker compose up -d
               
                
            - name: Show Allure URL
              run: echo "https://chaseqa.duckdns.org/allure/orangehrm-${{ env.NEW_TAG }}"
                
            - name: Cleanup old reports
              run: |
                ls -dt /opt/allure-reports/orangehrm-* | tail -n +11 | xargs rm -rf
                
            - name: Stop Selenium
              if: always()
              run: docker rm -f selenium
            
        